name: MLOps Workflow
on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main

jobs:
  build:
    env:
      supabase_url: ${{ secrets.SUPABASE_URL }}
      supabase_key: ${{ secrets.SUPABASE_KEY }}
      DAGSHUB_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      DAGSHUB_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      # MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      # MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.21'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          pip install -e .
      - name: Train model
        run: |
          uv run main.py train
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download model artifact
        uses: actions/download-artifact@v2
        with:
          name: trained-model
          path: models/
      - name: Infer model
        run: |
          uv run main.py infer
